# Generated by Django 4.2.5 on 2023-09-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='url',
            field=models.TextField(),
        ),
    ]
